### ISSUE TITLE
Will you publish it on NPM? 

### ISSUE THREAD

**Issue by undefinedExpert** [ndrwtrsk/SpringExam#1]
my node_modules require more fuel

**Comment by ndrwtrsk** [comment]
Yes. Especially for you.
W dniu śr., 29.08.2018 o 21:15 Emanuel Slotwinski <notifications@github.com>
napisał(a):

**Comment by undefinedExpert** [comment]
Will IT be blazing fast?

**Comment by ndrwtrsk** [comment]
No. Very slow.
W dniu czw., 30.08.2018 o 09:26 Emanuel Slotwinski <notifications@github.com>
napisał(a):

**Comment by undefinedExpert** [comment]
What's the point then putting IT on npm? On npm you'll find only blazing fast packages with 101% test coverage. Please do upload when it will be more efficient.
